# Generated by Django 5.0.2 on 2024-03-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(choices=[('pr', 'Preto'), ('br', 'Pranco'), ('ci', 'Cinza'), ('ma', 'Marrom'), ('gr', 'Gengibre'), ('li', 'Listrado'), ('am', 'Amarelo'), ('ve', 'Vermelho'), ('az', 'Azul'), ('lar', 'Laranja'), ('ro', 'Rosa'), ('ro', 'Roxo'), ('ver', 'Verde'), ('ma', 'Malhado')], max_length=3),
        ),
    ]
